/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fastcompress_FastCompress */

#ifndef _Included_fastcompress_FastCompress
#define _Included_fastcompress_FastCompress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fastcompress_FastCompress
 * Method:    hash64
 * Signature: ([BIIJ)J
 */
JNIEXPORT jlong JNICALL Java_fastcompress_FastCompress_hash64
  (JNIEnv *, jclass, jbyteArray, jint, jint, jlong);

/*
 * Class:     fastcompress_FastCompress
 * Method:    hash64Direct
 * Signature: (Ljava/nio/ByteBuffer;IIJ)J
 */
JNIEXPORT jlong JNICALL Java_fastcompress_FastCompress_hash64Direct
  (JNIEnv *, jclass, jobject, jint, jint, jlong);

/*
 * Class:     fastcompress_FastCompress
 * Method:    compressLZ4
 * Signature: ([BII[BI)I
 */
JNIEXPORT jint JNICALL Java_fastcompress_FastCompress_compressLZ4
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     fastcompress_FastCompress
 * Method:    decompressLZ4
 * Signature: ([BII[BII)I
 */
JNIEXPORT jint JNICALL Java_fastcompress_FastCompress_decompressLZ4
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     fastcompress_FastCompress
 * Method:    getLZ4MaxCompressedSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_fastcompress_FastCompress_getLZ4MaxCompressedSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     fastcompress_FastCompress
 * Method:    compressZstd
 * Signature: ([BII[BII)I
 */
JNIEXPORT jint JNICALL Java_fastcompress_FastCompress_compressZstd
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     fastcompress_FastCompress
 * Method:    decompressZstd
 * Signature: ([BII[BII)I
 */
JNIEXPORT jint JNICALL Java_fastcompress_FastCompress_decompressZstd
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
